/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#abadaf",
        "surface-tint": "#4647d3",
        "on-tertiary": "#ffeef4",
        "tertiary-dim": "#882a69",
        "surface-dim": "#d0d5d8",
        "surface-container-low": "#eef1f3",
        "inverse-primary": "#8083ff",
        "surface": "#f5f7f9",
        "on-tertiary-container": "#63054a",
        "error-dim": "#a70138",
        "tertiary-fixed": "#ff8ed2",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffc1d6",
        "primary-dim": "#3939c7",
        "primary-container": "#9396ff",
        "on-error-container": "#510017",
        "on-tertiary-fixed-variant": "#6e1354",
        "on-background": "#2c2f31",
        "primary-fixed-dim": "#8387ff",
        "primary-fixed": "#9396ff",
        "on-surface": "#2c2f31",
        "surface-variant": "#d9dde0",
        "on-primary-fixed-variant": "#0e009d",
        "surface-container": "#e5e9eb",
        "inverse-on-surface": "#9a9d9f",
        "surface-container-high": "#dfe3e6",
        "on-secondary": "#ffeff2",
        "on-primary": "#f4f1ff",
        "surface-bright": "#f5f7f9",
        "on-error": "#ffefef",
        "on-tertiary-fixed": "#3b002b",
        "on-secondary-fixed": "#6b003e",
        "secondary": "#b00d6a",
        "on-secondary-fixed-variant": "#9e005e",
        "secondary-fixed-dim": "#ffaccb",
        "tertiary-fixed-dim": "#ef81c4",
        "background": "#f5f7f9",
        "tertiary-container": "#ff8ed2",
        "on-primary-container": "#0a0081",
        "surface-container-highest": "#d9dde0",
        "secondary-fixed": "#ffc1d6",
        "tertiary": "#963776",
        "outline": "#747779",
        "on-surface-variant": "#595c5e",
        "error": "#b41340",
        "secondary-dim": "#9d005d",
        "primary": "#4647d3",
        "error-container": "#f74b6d",
        "on-secondary-container": "#8e0054",
        "inverse-surface": "#0b0f10",
        "on-primary-fixed": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}